apiVersion: v1
kind: Secret
metadata:
  name: middlewaredbsecret
type: Opaque
data:
  RDS_HOSTNAME: c3FsZGJhZG1pbi5teXNxbC5kYXRhYmFzZS5henVyZS5jb20K
  RDS_PORT: MzMwNgo=
  RDS_DB_NAME: dnJpdF9zcWxfZGIK
  RDS_USERNAME: c3FsYWRtaW4K
  RDS_PASSWORD: VnJpdGFkbWluQDExMTExCg==

##echo "abc" | bash64
