apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: appserver
  labels:
    env: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      env: backend
  template:
    metadata:
      labels:
        env: backend
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http
