apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: webserver
  labels:
    env: frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      env: frontend
  template:
    metadata:
      labels:
        env: frontend
    spec:
      containers:
      - image: httpd
        name: httpd
        ports:
        - containerPort: 80
          name: http