apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - image: {{ .Values.image }}:{{ .Values.image_version}}
        name: {{ .Values.name }}
        ports:
        - containerPort: {{ .Values.containerport }}
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: {{ .Values.containerport }}
  type: LoadBalancer
