apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: app-webserver
  labels:
    env: app-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      env: app-frontend
  template:
    metadata:
      labels:
        env: app-frontend
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http

---
apiVersion: v1
kind: Service
metadata:
  name: svc-app-frontend
spec:
  selector:
    env: app-frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer