apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware
  labels:
    app: middleware
spec:
  replicas: 2
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
      - name: middleware
        image: acr_login_servername/image_name:#{buildno}#
	env:
	- name: api_env
	  value: "azure-dev"
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: acr-secret
