apiVersion: apps/v1 
kind: Deployment
metadata:
  name: webserver2
  labels:
    app: web1
spec:
  replicas: 25
  selector:
    matchLabels:
      app: web1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http
