apiVersion: v1
kind: Pod
metadata:
  name: webserver3
  labels:
    app: app1
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
